package com.deepana.sagaorchestrator.service;

public enum SagaTrigger {
    INVENTORY_RESERVED,
    INVENTORY_FAILED,
    PAYMENT_SUCCESS,
    PAYMENT_FAILED,
    INVENTORY_RELEASED,
    PAYMENT_REFUNDED,
    ORDER_CONFIRMED,
    ORDER_CANCELLED,
    CANCEL_REQUESTED,
    ADMIN_RETRY_CONFIRM,
    ADMIN_RETRY_COMPENSATION,
    ADMIN_FORCE_RESOLVE
}
