UPDATE orders
SET status = CASE status
    WHEN 'INVENTORY_RESERVED' THEN 'CREATED'
    WHEN 'PAYMENT_SUCCESS_PENDING' THEN 'CREATED'
    WHEN 'PAYMENT_FAILED_PENDING' THEN 'CREATED'
    WHEN 'FAILED' THEN 'CANCELLED'
    ELSE status
END
WHERE status IN (
    'INVENTORY_RESERVED',
    'PAYMENT_SUCCESS_PENDING',
    'PAYMENT_FAILED_PENDING',
    'FAILED'
);
